### PR TITLE
Validate user-provided pit at the entry point

### LINKED ISSUE #503: Validate user-provided pit at the entry point
## Summary

`.kde_correction()` in `ppc-loo.R` crashes when all (or nearly all) PIT values are non-finite. After removing infinite values (lines 798-803), the function does not check whether enough finite values remain, leading to downstream errors.

## Steps to Reproduce

```r
bayesplot:::.kde_correction(c(Inf, -Inf, Inf), bw = "nrd0", grid_len = 128)

### PR DESCRIPTION
**Pull request by utkarshpawade**
Fixes #503 
## Summary

Validates user provided `pit` argument immediately when it is provided

### CODE REVIEW

**Comment by florence-bockting** [comment]
Hi @utkarshpawade, thanks for the PR. I provided a small discussion about your observation in the corresponding [Issue](https://github.com/stan-dev/bayesplot/issues/503#issuecomment-4125768208).

Probably you could adjust the PR accordingly.

File: R/ppc-loo.R
Comment (jgabry) [inline R/ppc-loo.R]: Here's another case

Comment (utkarshpawade) [reply R/ppc-loo.R]: Got it, working on it.

File: R/ppc-loo.R [hunk 1]
```diff
@@ -824,6 +816,10 @@ ppc_loo_ribbon <-
 
   xs <- (grid_breaks[2:n_breaks] + grid_breaks[1:(n_breaks - 1)]) / 2
 
+  if (all(is.na(bc_pvals))) {
```
Comment (jgabry) [inline R/ppc-loo.R]: Can you move this up a few lines to right after `bc_pvals` is created? Or is there a reason it comes after `n_breaks` and `xs` are computed?

File: NEWS.md [hunk 2]
```diff
@@ -1,5 +1,6 @@
 # bayesplot (development version)
 
+* Validate user-provided `pit` values in `ppc_loo_pit_data()` using `validate_pit()` to reject invalid inputs (non-numeric, out of range, NAs) at the entry point instead of in internal helpers.
```
Comment (jgabry) [inline NEWS.md]:
```suggestion
* Validate user-provided `pit` values in `ppc_loo_pit_data()` and `ppc_loo_pit_qq()`, rejecting non-numeric inputs, missing values, and values outside `[0, 1]`.
```

**Review by jgabry — CHANGES_REQUESTED** [review]

**Review by jgabry — APPROVED** [review]
